define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "NewAuthorizationButton": "NEW AUTHORIZATION",
    "DepartmentLabel" : "Department",
    "JobTitleLabel" : "Job Title",
    "ExecutiveLabel" : "Executive",
    "JJInternalExternalLabel" :"J&J Internal / External",
    "IVStatusLabel" : "IV Status",
    "IVAwardDateLabel" : "Date of IV Award",
    "FirstLastNameLabel" : "First and Last name",
    "CompanyEntryLabel" : "Company Entry",
    "ExceptionLabel" : "Exception under 6 months at J&J",
    "ConfirmationLabel" : "Confirmation that the application has been submitted for a paygrade of 24 or higher",
    "IVReasonLabel" : "Reason for i.V.",
    "JustificationLabel": "Justification for exceptions",
    "DrawsContractsOption": "Draws contracts for Janssen",
    "NegotiatedOption": "Negotiated for Janssen",
    "RepresentativeOption": "Representative",
    "ReleasePDFLabel": "Release pdf",
    "JobhistoryLabel": "Job history",
    "IVJustificationLabel": "Justification for i.V. all 3 per tick box",
    "LastReviewDateLabel": "Date of last review",  
    "ResultLabel": "Result of the last check",
    "IVWithdrawalDateLabel": "Date of IV withdrawal",
    "IVWithdrawalReasonLabel": "Reason for IV withdrawal",  
    "DatabaseHeader": "Database of i.V. authorization",  
    "SaveButton" : "SAVE",
    "DeleteRequestLabel" : "Are you sure you want to delete this request?",
    "DeleteRequestSuccessLabel" : "Request deleted successfully!",
    "DeleteButton": "Delete",
    "CancelButton": "Cancel",
    "RecordInsertionSuccessLabel": "Record inserted successfully!",
    "RecordUpdationSuccessLabel": "Record updated successfully!",
    "NameErrorMsg": "Name cannot be empty",
    "WWIDErrorMsg": "WWID cannot be empty",
    "DepartmentErrorMsg": "Department cannot be empty",
    "JobTitleErrorMsg": "Job Title cannot be empty",
    "ExecutiveErrorMsg": "Please select Executive",
    "JErrorMsg": "Please select J&J Internal / External",
    "CompanyErrorMsg": "Company Entry cannot be empty",
    "ExceptionErrorMsg": "Please select Exception under 6 months at J&J",
    "ReasonErrorMsg": "Reason Checkbox should be click",
    "JustificationErrorMsg": "Justification for exceptions cannot be empty",
    "IVStatusErrorMsg": "Please select IV Status",
    "DateOfIVAwardErrorMsg": "Date of IV Award cannot be empty",
    "ReleaseErrorMsg": "Release pdf cannot be empty",
    "JobHistoryErrorMsg": "Job history cannot be empty",
    "DateOfLastErrorMsg": "Date of last review cannot be empty",
    "ResultErrorMsg": "Please select Result of the last check",
    "DateOfWithdrawalErrorMsg": "Date of IV withdrawal cannot be empty",
    "ReasonForIVErrorMsg": "Reason for IV withdrawal cannot be empty"
  }
});